services:
  - type: web
    name: yolo-fastapi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
